### ISSUE TITLE
Someone can help me with the setup

### ISSUE THREAD

**Issue by Livitan** [Petrosz007/goblineer#7]
Hi, someone can help me with the setup, please... 
I have a PHP server, but I do not know how to set goblineer.

**Comment by Petrosz007** [comment]
Make sure you have set up MySQL properly, imported db.sql into it, filled
out dbh_github.php with your information and renamed it to dbh.php

If you still get errors look around this reddit thread, I have
troubleshooted problems there.
http://www.reddit.com/r/wowgoblins/comments/9bcpdz/-/e537kpe

**Comment by Livitan** [comment]
Hooray, has earned.Thanks for this app!
